namespace: default
nodes:
- node01
- node02
grafana:
  replicas: 1

    #honor_labels: true
custom_metrics:
  - name: testmetrics
    job_name: testjob
    labels:
      color: green
      priority: high
    alert_trigger_value: 500
    upper_limit_counter: 2000
  - name: anothertestmetrics
    job_name: anotherjob
    labels:
      color: black
      prority: low
    alert_trigger_value: 800
    upper_limit_counter: 2000

  - name: amitmetrics
    job_name: finaljob
    labels:
      color: black
      prority: low
    alert_trigger_value: 100
    upper_limit_counter: 1000

  - name: fastmetrics
    job_name: finaljob
    labels:
      color: black
      prority: low
    alert_trigger_value: 100
    upper_limit_counter: 200
      #proxies:
      #  http_proxy: http://172.20.73.196:3128
      #  https_proxy: http://172.20.73.196:3128
      #  no_proxy: ".svc.cluster.local"
