namespace: default
nodes:
- node01
- node02
grafana:
  replicas: 1

honor_labels: true # If you turn it off the labels passed during POST request of metrics towards pushgateway will come as exported_
#Notification System for Alertmanager
slack:
  webhook_url: "https://hooks.slack.com/services/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"
  channel: "#monitoring"

custom_metrics:
  - name: testmetrics
    job_name: testjob
    labels:
      color: green
      priority: high
        #      experiment: "false"
    alert_trigger_value: 500
    upper_limit_counter: 2000
  - name: anothertestmetrics
    job_name: anotherjob
    labels:
      color: black
      prority: low
        # experiment: "false"
    alert_trigger_value: 800
    upper_limit_counter: 2000

  - name: amitmetrics
    job_name: finaljob
    labels:
      color: black
      prority: low
        #experiment: "false"
    alert_trigger_value: 100
    upper_limit_counter: 1000

  - name: fastmetrics
    job_name: finaljob
    labels:
      color: black
      prority: low
        #experiment: "true"
    alert_trigger_value: 100
    upper_limit_counter: 200
      #proxies:
      #  http_proxy: http://172.20.73.196:3128
      #  https_proxy: http://172.20.73.196:3128
      #  no_proxy: ".svc.cluster.local"
