---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertconfig
data:
  alertmanager.yml: |
    route:
      group_by: ['alertname']
      group_wait: 1m
      group_interval: 1m
      repeat_interval: 1h
      receiver: "web"
      routes:
      - match:
          team: dev
        group_by: [team]
        receiver: slack
    receivers:
      - name: "web"
        webhook_configs:
          - url: 'http://127.0.0.1:5001/'
      - name: slack
        slack_configs:
        - api_url: "{{ .Values.slack.webhook_url }}"
          channel: "{{ .Values.slack.channel }}"
          title: 'Alert Name {{ `Group Labels = {{ .GroupLabels.team }}` }}'
          text: '{{ `{{ range .Alerts }} {{ .Annotations.message }} {{ "\n" }} {{ end }}` }}'
          http_config:
            proxy_url: "http://172.20.73.196:3128"
            tls_config:
              insecure_skip_verify: true
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    alertmanager: alertmanager
  ports:
  - port: 80
    targetPort: 9093
---
apiVersion: v1
kind: Pod
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    alertmanager: alertmanager
spec:
  containers:
  - name: alertcontainer
    image: docker.io/amitkumarjo1994/testbox:latest
    command: ["./alertmanager"]
    volumeMounts:
    - name: alertconfig
      mountPath: /opt/alertmanager.yml
      subPath: alertmanager.yml
  volumes:
  - name: alertconfig
    configMap:
      name: alertconfig
