{{- if .Values.grafana }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://promsvc.{{ .Values.namespace }}.svc.cluster.local
        isDefault: true
{{- end }}
