
{{- if .Values.grafana }}
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: grafana-datasources
#  namespace: {{ .Values.namespace }}
#data:
#  datasources.yaml: |
#    apiVersion: 1
#    datasources:
#      - name: Prometheus
#        type: prometheus
#        url: http://promsvc.{{ .Values.namespace }}.svc.cluster.local
#        isDefault: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      namespace: {{ .Values.namespace }}
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          subPath: datasources.yaml
      volumes:
      - name: grafana
        configMap:
          name: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
{{- end }}
