---
apiVersion: v1
kind: Service
metadata:
  name: promsvc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    promnode: promnode
  ports:
  - port: 80
    targetPort: 9090
---
apiVersion: v1
kind: Pod
metadata:
  name: myprompod
  namespace: {{ .Values.namespace }}
  labels:
    promnode: promnode
spec:
  containers:
  - name: mymachine
    image: docker.io/amitkumarjo1994/testbox:latest
    command: ["./prometheus"]
    volumeMounts:
    - name: config
      mountPath: /opt/prometheus.yml
      subPath: prometheus.yml
    - name: config
      mountPath: /opt/rules.yml
      subPath: rules.yml
  - name: newmachine
    image: docker.io/amitkumarjo1994/pushg:latest
    command: ["bash","-c","./pushmetrics.sh"]
    env:
    - name: NUMBER
      value: "{{ .Values.upper_limit_counter }}"
    - name: METRICS_NAME
      value: {{ .Values.custom_metric_name }}
    - name: NAMESPACE
      value: {{ .Values.namespace }}
  volumes:
  - name: config
    configMap:
      name: promconfig
