apiVersion: v1
kind: ConfigMap
metadata:
  name: promconfig
  namespace: {{ .Values.namespace }}
data:
  sd_file.json: |
    [
        {
            "targets": [
                "dhost01",
                "dhost02"
            ],
            "labels": {
                "newlabel": "value"
            }
        }
    ]
  rules.yml: |
    groups:
    - name: SAMPLE ALERTS
      rules:
{{- range $_, $item := .Values.custom_metrics }}
      - alert: Alert-{{ $item.name }}
        expr: {{ $item.name }} > {{ $item.alert_trigger_value }}
        annotations:
          message: "The is Alert message for {{ $item.name }}  and value is {{ `{{ .Value }}` }} for instance {{ `{{ .Labels.job }}` }}"
        labels:
          category: {{ $item.category }}
{{- end }}

  prometheus.yml: |
    {{- $svclist := list }}  # Initialize the list
    {{- range $_, $item := .Values.nodes }}
      {{- $svclist = append $svclist (printf "\"%s.%s.svc.cluster.local\"" $item $.Values.namespace) }}  # Append each item with the correct format
    {{- end }}
    
    global:
      scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
    rule_files:
    - "rules.yml"
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager.default.svc.cluster.local'
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [{{ join "," $svclist }}]  # Join the list with commas
            labels:
              quality: good
              kumar: amit
      - job_name: "pushgateway"
        honor_labels: {{ .Values.honor_labels | default false }}
        static_configs:
          - targets: ["pushgateway.default.svc.cluster.local"]  # Join the list with commas
            labels:
              experiment: true

      - job_name: "newtargets"
        file_sd_configs:
          - files:
              - "sd_file.json"

