{{- $finalresult := "" }}
{{- range $_, $item := .Values.custom_metrics }}
  {{- $dict := $item.labels }}   
  {{- $pairs := list }}       

  {{- range $key, $value := $dict }}
    {{- $pairs = append $pairs (printf "%s-%s" $key $value) }}   
  {{- end }}

  {{- $result := printf "%s:%s:%s:%s:%s" ($item.job_name) ($item.alert_trigger_value|toString) ($item.upper_limit_counter|toString) $item.name (join "-" $pairs) }}

  {{- $finalresult = printf "%s/%s" $finalresult $result }}
{{- end }}


---
apiVersion: v1
kind: Service
metadata:
  name: promsvc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    promnode: promnode
  ports:
  - port: 80
    targetPort: 9090
---
apiVersion: v1
kind: Pod
metadata:
  name: myprompod
  namespace: {{ .Values.namespace }}
  labels:
    promnode: promnode
spec:
  containers:
  - name: mymachine
    image: docker.io/amitkumarjo1994/testbox:latest
    command: ["./prometheus"]
    volumeMounts:
    - name: config
      mountPath: /opt/prometheus.yml
      subPath: prometheus.yml
    - name: config
      mountPath: /opt/rules.yml
      subPath: rules.yml
    - name: config
      mountPath: /opt/sd_file.json
      subPath: sd_file.json
  - name: newmachine
    image: docker.io/amitkumarjo1994/pushgscript:latest
    command: ["bash","-c","./pushmetrics.sh"]
    env:
    - name: NAMESPACE
      value: {{ .Values.namespace }}
    - name: OS
      value: {{ $finalresult }}
  volumes:
  - name: config
    configMap:
      name: promconfig
