---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    pushgateway: pushgateway
  ports:
  - port: 80
    targetPort: 9091
---
apiVersion: v1
kind: Pod
metadata:
  name: pushgateway
  namespace: {{ .Values.namespace }}
  labels:
    pushgateway: pushgateway
spec:
  containers:
  - name: pushgcontainer
    image: docker.io/amitkumarjo1994/testbox:latest
    command: ["./pushgateway"]
